import { adminAuth } from "@/lib/firebase/admin";
import { supabase } from "@/lib/supabase";

export async function getUserFromRequest(req: Request) {
    const authHeader = req.headers.get("authorization");
    if (!authHeader) return null;

    const token = authHeader.replace("Bearer ", "");
    try {
        const decodedToken = await adminAuth.verifyIdToken(token);
        return decodedToken;
    } catch (error) {
        console.error("Error verifying token:", error);
        return null;
    }
}

export async function getSupabaseUserFromFirebaseUid(firebaseUid: string, email?: string, name?: string, avatarUrl?: string) {
    // 1. Try to find the user in profiles by firebase_uid
    const { data: user, error } = await supabase
        .from("profiles")
        .select("*")
        .eq("firebase_uid", firebaseUid)
        .single();

    if (user) return user;

    // 2. If not found, create a new profile
    // Note: We assume the DB has been migrated to allow null user_id or we handle it.
    // Ideally, we should have a 'firebase_uid' column in profiles.

    if (!email) throw new Error("Email is required to create a user");

    const { data: newUser, error: createError } = await supabase
        .from("profiles")
        .insert({
            firebase_uid: firebaseUid,
            email: email, // Assuming 'email' column was added to profiles
            full_name: name, // Assuming 'full_name' exists in profiles
            avatar_url: avatarUrl,
            // id will be auto-generated by gen_random_uuid() if configured
        })
        .select()
        .single();

    if (createError) {
        console.error("Error creating user in Supabase:", createError);
        throw createError;
    }

    return newUser;
}